name: test_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your other packages
  flutter_tts: ^3.8.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  intl: ^0.19.0 # I've updated your packages to more recent, compatible versions
  table_calendar: ^3.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.35.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # --- 【關鍵修正】---
  # assets 區塊必須要像這樣，被完整地包在 flutter: 區塊的「裡面」。
  # "assets:" 本身，要跟上面的 "uses-material-design:" 對齊。
  assets:
    # "- image/icon/" 前面有兩個空格，這是固定的格式。
    - image/icon/
    - image/page_icon/

